### ISSUE TITLE
problem with main.php

### ISSUE THREAD

**Issue by newtonsart** [quadcoreside/QuadCore-Web-SQLi-Injecter-DB-Dumper#2]

**Comment by newtonsart** [comment]
php main.php 
PHP Notice:  Undefined index: REQUEST_URI in /home/lolart/Downloads/QuadCore-Web-SQLi-Injecter-DB-Dumper/core/Dispatcher.php on line 9
PHP Notice:  Undefined offset: 0 in /home/lolart/Downloads/QuadCore-Web-SQLi-Injecter-DB-Dumper/core/Dispatcher.php on line 82
/home/lolart/Downloads/QuadCore-Web-SQLi-Injecter-DB-Dumper/request/controller/Controller.php

**Comment by quadcoreside** [comment]
Check your PHP version
