### ISSUE TITLE
How to fix tool ?

### ISSUE THREAD

**Issue by xdevil999** [quadcoreside/QuadCore-Web-SQLi-Injecter-DB-Dumper#3]
/home/tringloc/public_html/quad/QuadCore-Web-SQLi-Injecter-DB-Dumper-master/request/controller/AppController.php

**Comment by quadcoreside** [comment]
can you give me more information ?

**Comment by xdevil999** [comment]
When I put your tool on my host it got an error like that

**Comment by xdevil999** [comment]
how to upload quadcore-web sql injection tool to cpanel




Vào Th 5, 12 thg 3, 2020 vào lúc 10:31 QuadCore MSB <
notifications@github.com> đã viết:

**Comment by quadcoreside** [comment]
Can you activate debugging, in order to have more information please

**Comment by quadcoreside** [comment]
Try to place everything in a single folder in your "public_html"
